logging:
  pattern:
    level: "%5p [traceId=%X{traceId:-}, spanId=%X{spanId:-}]"
management:
  endpoint:
    health:
      show-details: never
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,prometheus,metrics,info
server:
  tomcat:
    accept-count: 2000
    connection-timeout: 5000
    keep-alive-timeout: 5000
    max-connections: 20000
    max-keep-alive-requests: 1000
    mbeanregistry:
      enabled: true
    threads:
      max: 500
      min-spare: 100
spring:
  application:
    name: SpringTomcat
  threads:
    virtual:
      enabled: false